datos = [
    {"Tematica": "Programacion",
    "Palabra a descubrir": "variable"},
    {"Tematica": "Programacion",
    "Palabra a descubrir": "funcion"},
    {"Tematica": "Programacion",
    "Palabra a descubrir": "bucle"},
    {"Tematica": "Programacion",
    "Palabra a descubrir": "condicion"},
    {"Tematica": "Videojuego",
    "Palabra a descubrir": "nivel"},
    {"Tematica": "Videojuego",
    "Palabra a descubrir": "consola"},
    {"Tematica": "Videojuego",
    "Palabra a descubrir": "mision"},
    {"Tematica": "Videojuego",
    "Palabra a descubrir": "jugador"},
    {"Tematica": "Deportes",
    "Palabra a descubrir": "futbol"},
    {"Tematica": "Deportes",
    "Palabra a descubrir": "basquet"},
    {"Tematica": "Deportes",
    "Palabra a descubrir": "handball"},
    {"Tematica": "Deportes",
    "Palabra a descubrir": "tenis"},
    {"Tematica": "Historia",
    "Palabra a descubrir": "revolucion"},
    {"Tematica": "Historia",
    "Palabra a descubrir": "monarquia"},
    {"Tematica": "Historia",
    "Palabra a descubrir": "dictadura"},
    {"Tematica": "Historia",
    "Palabra a descubrir": "colonia"},
]



